[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
AlgebraicPetri = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
ApproxBayes = "f5f396d3-230c-5e07-80e6-9fadf06146cc"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
Bridge = "2d3116d5-4b8f-5680-861c-71f149790274"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DiffEqJump = "c894b116-72e5-5b58-be3c-e6d8d4ac2b12"
DiffEqParamEstim = "1130ab10-4a5a-5621-a13d-e4788d82bd4c"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
Fleck = "5bb9b785-358c-4fee-af0f-b94a146244a8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GpABC = "e850a1a4-d859-11e8-3d54-a195e6d045d3"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LabelledArrays = "2ee39098-c373-598a-b85f-a56591580800"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
NestedSamplers = "41ceaf6f-1696-4a54-9b49-2e7a9ec3782e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Petri = "4259d249-1051-49fa-8328-3f8ab9391c33"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
SimJulia = "428bdadb-6287-5aa5-874b-9969638295fd"
SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
Soss = "8ce77f84-9b61-11e8-39ff-d17a774bf41c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
